config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :projects do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :news_items, as: :news_itemable

  after_create :create_news_item

  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :commentable_id, presence: true, numericality: { only_integer: true }
  validates :commentable_type, presence: true, inclusion: { in: ["Project"] }

  def create_news_item
    NewsItem.create(title: "New comment on #{self.commentable.name}", body: self.body, news_itemable_type: "Comment", news_itemable_id: id, project_id: self.commentable_id, user_id: self.user_id)
  end
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  belongs_to :project
  belongs_to :news_itemable, polymorphic: { limit: [:Comment, :Project] }
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :news_itemable_id, presence: true, numericality: { only_integer: true }
  validates :news_itemable_type, presence: true, inclusion: { in: ["Comment", "Project"] }
  validates :project_id, presence: true, numericality: { only_integer: true }
  validates :user_id, presence: true, numericality: { only_integer: true }
  validate  :news_itemable_must_be_allowed_class

  def news_itemable_must_be_allowed_class
    unless news_itemable.is_a?(Comment) || news_itemable.is_a?(Project)
      errors.add(:news_itemable, "must be a Comment or a Project")
    end
  end

  def comment?
    self.news_itemable_type == "Comment"
  end

  def project?
    self.news_itemable_type == "Project"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :news_items, as: :news_itemable

  VALID_STATUSES = ["pending","new", "active", "completed", "archived"]

  validates :name, presence: true, length: { minimum: 4 }
  validates :status, presence: true, inclusion: { in: VALID_STATUSES }
  validates :description, presence: true, length: { minimum: 10 }

  def create_news_item(user)
    if self.saved_change_to_status?
      ni = NewsItem.create(title: "#{self.name} project status update", body: "#{self.name} status changed to #{self.status}", news_itemable_type: "Project", news_itemable_id: id, project_id: self.id, user_id: user.id)
      if ni.persisted?
        Rails.logger.info "News item created: #{ni.inspect}"
      else
        Rails.logger.info "News item not created: #{ni.errors.full_messages}"
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, as: :commentable
  has_many :news_items, as: :newsable

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project, only: [:create, :destroy]

  def create
    @comment = @project.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment was successfully created."
      redirect_to @project, notice: "Comment was successfully created."
    else
      flash[:alert] = "Error creating comment. #{@comment.errors.full_messages.to_sentence}"
      redirect_to @project, alert: "Error creating comment. #{@comment.errors.full_messages.to_sentence}"
    end
  end

  def destroy
    @comment = @project.comments.find(params[:id])
    @comment.destroy

    redirect_to @project, notice: "Comment was successfully deleted."
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @news_items = NewsItem.where(project_id: @project.id)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'index'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, :notice => "Successfully destroyed project."
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      @project.create_news_item(current_user)
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_item_helper.rb
module NewsItemHelper
  def news_item_heading
    case self.news_itemable_type
    when "Comment"
      "Comment"
    when "Project"
      "Status Update"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyConverstation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>

  <% if alert %>
    <div class="alert"><%= alert %></div>
  <% end %>

  <%= yield %>
  </body>
</html>

app/views/news_items/_news_item.html.erb
<li><span></span>
  <div>
    <div class="title"><%= news_item.title %></div>
    <div class="info"><%= news_item.body %></div>
    <div class="type"><%= news_item.user.email %></div>
  </div> <span class="number"><span><%= news_item.created_at.strftime("%x") %></span></span>
</li>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["pending","new", "active", "completed", "archived"] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: 'form', locals: { project: @project} %>

app/views/projects/index.html.erb
<div class="table-container">
  <h2>Project List</h2>
  <ul class="responsive-table">
    <li class="table-header">
      <div class="col col-1">Name</div>
      <div class="col col-2">Description</div>
      <div class="col col-3">Status</div>
      <div class="col col-4">Actions</div>
    </li>
    <% if @projects %>
      <% @projects.each do |project| %>
        <li class="table-row">
          <div class="col col-1" data-label="Name"><%= project.name %></div>
          <div class="col col-2" data-label="Description"><%= project.description %></div>
          <div class="col col-3" data-label="Status"><%= project.status %></div>
          <div class="col col-4" data-label="Actions">
            <%= link_to "Show", project %>
            <%= link_to "Edit", edit_project_path(project) %>
            <%= link_to "Delete", project, method: :delete, data: { confirm: "Are you sure you want to delete this project?" } %></div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div id="actions">
    <%= link_to "New Project", new_project_path %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_with(model: @project, url: projects_path) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Project::VALID_STATUSES.map { |k| [k.humanize, k] }) %>
  </div>

  <div class="actions">
    <%= form.submit "Create Project" %>
  </div>
<% end %>

<%= link_to "Back", projects_path %>

app/views/projects/show.html.erb
<div class="container">
  <div class="project-header">
    <div class="project-header-content">
      <h1 class="project-header-title"><%= @project.name %></h1>
      <p class="project-header-description">P<%= @project.description %></p>
      <div class="project-status">
        <%= render partial: "form", locals: { project: @project } %>
      </div>
    </div>
  </div>
  <ul>
  <% @news_items.each do |ni| %>
    <%= render partial: "news_items/news_item", locals: { news_item: ni } %>
  <% end %>
  </ul>
  <div class="comments">
    <h3>Add Comment</h3>
    <%= form_with(model: [@project, Comment.new], url: project_comments_path(@project)) do |form| %>
    <%= form.text_area :body, placeholder: "Add a comment", class: "comment-form-input" %>
    <%= form.submit "Add Comment", class: "comment-form-submit" %>
    <% end %>
  </div>
</div>